### ISSUE TITLE
permit certain words

### ISSUE THREAD

**Issue by stackedactors1** [snipe/banbuilder#29]
I'm currently using this library.  How can I let certain words pass? like 'hell' if I check 'Michelle'  it thinks it is a bad word.  How can I check for just 'hell' and/or let 'hell' be acceptable?

**Comment by davidtrushkov** [comment]
To do that, go into the ` vendor/snipe/banbuilder/src/dict/ ` directory, or where ever it is located in your setup, and in there, there will be files for each language that is supported by this package. In those files are a list of bad words. Find the word your looking for, so in this example "hell", and delete it from the array. That will stop checking that word.

**Comment by snipe** [comment]
Whitelisting was introduced in v2.2.4
