### ISSUE TITLE
"analytics" et similia censored?

### ISSUE THREAD

**Issue by oprog** [snipe/banbuilder#33]
use Snipe\BanBuilder\CensorWords;
$censor = new CensorWords;
$string = $censor->censorString("analytics");

print_r($string);

result:

Array
(
    [orig] => analytics
    [clean] => ****ytics
    [matched] => Array
        (
            [0] => anal
        )

)

Maybe I'm missing something. Is there a way to avoid that or the script just match a bad word wherever it is in the sentence, even inside another word?

Thanks.

**Comment by kevindaus** [comment]
check this one out. I think you have the same issue.
https://github.com/snipe/banbuilder/issues/40

try passing true to the second param
$censored = $censor->censorString('analytics', true);
