### ISSUE TITLE
Please create a new release.

### ISSUE THREAD

**Issue by geo-at-github** [snipe/banbuilder#34]
The current Release (2.2.3) contains a lot of syntax errors and does not work (missing de.php, errors in fi.php and no.php).

Can you please make a new release based on dev-master (that one works and has all the proper fixes)?

Why am I reporting this?
It would be nice to be able to use versions in composer without risk like "snipe/banbuilder": "2.2.*"
I am not a big fan of dev-master since I have suffered through broken package dependencies too much (especially in team projects with lot´s of reinstalls) ;-)

**Comment by AronNovak** [comment]
BanBuilder is one of the most popular open-source profanity filters, it deserves a fresh release certainly.

**Comment by AronNovak** [comment]
https://github.com/AronNovak/banbuilder/archive/2.3.zip
a straight fork from current master

**Comment by snipe** [comment]
https://github.com/snipe/banbuilder/releases/tag/2.2.4
