### ISSUE TITLE
Problem With 'Hello'

### ISSUE THREAD

**Issue by codingbrains2-design** [snipe/banbuilder#40]
I created a PHP file and added some bad words using array_push().
when i input 'hello', it converts it into ****.
but i don't have hello word in the badwords array.

**Comment by haridarshan21** [comment]
@raghucodingbrains  
In such cases, check for full words like this

```php
$censored = $censor->censorString('hello', true);
```
This will not censor hello word

**Comment by rquast** [comment]
Is there a feature where a banned word could also be associated with a list of words that are whitelisted? Hello was the first word I tried, but if hell (sorry to offend anyone here) could be associated with hello and check the string for hello, that may get around the issue.

**Comment by rquast** [comment]
https://github.com/snipe/banbuilder/pull/41 - that pull request should help sort out this issue.
